name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (e.g. dev, test, prod)"
        required: true
        type: string

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init

      - name: Select or Create Workspace
        run: |
          terraform workspace select "${{ github.event.inputs.environment }}" || terraform workspace new "${{ github.event.inputs.environment }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars" -input=false

      - name: Terraform Apply
        run: terraform apply -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve
